const names = [
  'Lisette',
  'Cecelia',
  'Samantha',
  'Helen',
  'Nicole',
  'Colette',
  'Cindy',
  'Mary',
  'Remi',
  'Alix',
  'Ana',
  'Daphne',
  'Parker',
  'Betty',
  'Maia',
  'Eve',
  'Genevieve',
  'Ada',
  'Hunter',
  'Stella',
  'Harlow',
  'Brynn',
  'Quinn',
  'Violet',
  'Yvette',
];

const hairstyleFront = [
  'side swept bangs',
  'face framing bangs',
  'baby bangs',
  'choppy, tousled bangs',
  'lash skimming bangs',
  'curtain bangs',
  'long, piecy bangs',
  'curly bangs',
  'faux bangs',
  'thick mid-length bangs',
  'long airy bangs',
  'short bangs',
  'asymmetrical bangs',
];

const hairstyleBack = [
  'tight bun',
  'loose bun',
  'deux mandu',
  'a french braid',
  'a long bob',
  'a shoft bob',
  'shoulder length hair',
  'waist length hair',
  'a short ponytail',
  'a long ponytail',
  'long twin ponytails',
  'a single long braid',
  'fun curls',
  'a princess braid',
];

const skintone = [
  'porcelain',
  'pale',
  'olive',
  'rosy',
  'sunkissed',
  'fair',
  'golden',
  'bronzed',
  'cocoa',
];

const cupsize = [
  'AA',
  'A', 'A', 'A', 'A', 'A',
  'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
  'C', 'C', 'C', 'C',
  'D', 'D', 'D',
  'E', 'E',
  'F',
  'G',
];

const attribute = [
  'nun',
  'virgin',
  'office',
  'researcher',
  'gamer',
  'cosplayer',
  'pilot',
  'sailor',
  'replicant',
  'showgirl',
  'camgirl',
  'youtuber',
  'streamer',
  'programmer',
  'hacker',
  'assassin',
  'soldier',
  'fortune teller',
  'witch',
  'escort',
  'pharmacist',
  'model',
  'supermodel',
  'fashion designer',
  'entrepreneur',
  'CEO',
  'barista',
  'bartender',
  'hostess',
  'waitress',
  'actress',
  'singer',
  'astronaut',
  'racer',
  'mechanic',
  'painter',
  'sculptor',
  'working girl',
  'voice actress',
  'nurse',
  'doctor',
  'captain',
  'hologram',
  'AI',
  'dominatrix',
  'sugar baby',
  'gold digger',
  'perpetual catfish',
  'perpetual adulterer',
  'single mom',
  'widow',
  'schoolgirl',
  'step-mom',
  'step-sister',
  'cook',
  'baker',
  'teacher',
  'lingerie model',
  'pornstar',
  'neko',
  'furry',
  'catgirl',
  'vampire',
  'idol',
  'miss universe',
  'trap',
  'fishy trap',
  'alien babe',
  'ghost',
  'jailbait',
  'murderer',
  'sex doll',
  'rich girl',
  'desperate housewife',
  'magical girl',
];

const disposition = [
  'adorable',
  'strict',
  'teasing',
  'tsundere',
  'fraile',
  'vicious',
  'domineering',
  'manipulative',
  'naturally cute',
  'irresistibly cute',
  'drop dead gorgeous',
  'fair',
  'needy',
  'clingy',
  'optimistic',
  'manic pixie dreamy',
  'creative',
  'kinky',
  'sleazy',
  'easy',
  'food-driven',
  'ambitious',
  'prodigy',
  'genius',
  'proud',
  'submissive',
  'serious',
  'gothic',
  'ditsy',
  'fit',
  'curvy',
  'psycho',
  'perfectionist',
  'controlling',
  'cheating',
  'smothering',
  'wifey',
  'laid back',
  'constantly high',
  'constantly drunk',
  'perfect',
  'cock-hungry',
  'cum-hungry',
  'bondage-loving',
  'horny',
  'asexual',
  'bisexual',
  'polyamorous',
  'super religious',
  'dicc succing',
  'textbook',
  'inexperienced',
  'flirty',
];

const vice = [
  'smokes cigarettes',
  'drinks heavily',
  'smokes marijuana',
  'masochistic',
  'manic depressive',
  'bipolar',
  'consumes a lot of porn',
  'disloyal',
  'murderous',
  'blackmailing',
  'short tempered',
  'can\'t cook',
  'anorexic',
  'blind',
  'deaf',
  'expensive',
  'cheap',
  'hopeless',
  'sweats',
  'perfectionist',
  'OCD',
  'sex maniac',
  'blood thirsty',
  'slow',
  'prude',
  'screamer',
  'squirter',
  'easily jealous',
  'untrustworthy',
  'trust issues',
  'daddy issues',
  'mommy issues',
  'nazi',
  'self-harming',
  'bulemic',
  'drug abusig',
  'hospital bound',
  'hypochondriac',
  'xenophobic',
  'soul sucking',
  'flatulent',
  'distracted',
  'weak',
  'angry',
  'resentful',
  'shameful',
  'narcoleptic',
  'insomniac',
  'obscene',
  'gambling',
  'speed demon',
  'suicidal',
  'piered',
];

// const height = () => { };
// 152 to 180

// const weight = () => { };
// 49 to 80
